stages:
  - testing
  - documentation

python_latest:
    stage: testing
    image: python:latest
    
    before_script:
      - python -V               # Print out python version for debugging
      - pip install -r requirements.txt
    
    script:
    - python ./tests/player.py
    - python ./tests/speed.py
    
python_rc:
    stage: testing
    image: python:rc
    
    before_script:
      - python -V               # Print out python version for debugging
      - pip install -r requirements.txt
    
    script:
    - python ./tests/player.py
    - python ./tests/speed.py
    
    
    allow_failure: true
    
python_3.6:
    stage: testing
    image: python:3.6
    
    before_script:
      - python -V               # Print out python version for debugging
      - pip install -r requirements.txt
    
    script:
    - python ./tests/player.py
    - python ./tests/speed.py

    
python_3.5:
    stage: testing
    image: python:3.5
    
    before_script:
      - python -V               # Print out python version for debugging
      - pip install -r requirements.txt
    
    script:
    - python ./tests/player.py
    - python ./tests/speed.py
    

python_3.4:
    stage: testing
    image: python:3.4
    
    before_script:
      - python -V               # Print out python version for debugging
      - pip install -r requirements.txt
    
    script:
    - python ./tests/player.py
    - python ./tests/speed.py
    
    
python_2.x:
    stage: testing
    image: python:2
    
    before_script:
      - python -V               # Print out python version for debugging
      - pip install -r requirements.txt
    
    script:
    - python ./tests/player.py
    - python ./tests/speed.py
    
    
    allow_failure: true
    
documentation:
    stage: documentation
    image: python:latest
    
    before_script:
      - python -V               # Print out python version for debugging
      - pip install -r requirements.txt
    
    script:
    - pip install sphinx sphinx-rtd-theme
    - cd docs/
    - make html
    - mv _build/html/ ../public/